//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_KUTUPHANE.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYayinevi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblYayinevi()
        {
            this.TblKitap = new HashSet<TblKitap>();
        }
    
        public byte ID { get; set; }
        public string YAYINEVI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKitap> TblKitap { get; set; }
    }
}
